[package]
name = "evm"
version = "0.11.0-beta.2"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "SputnikVM - a Portable Blockchain Virtual Machine"
repository = "https://github.com/etclabscore/sputnikvm"
keywords = ["no_std", "ethereum"]
edition = "2018"

[lib]
name = "evm"

[dependencies]
sha3 = "0.6"
sha2 = "0.6"
ripemd160 = "0.6"
digest = "0.6"
ethereum-block-core = { version = "0.2.0", default-features = false }
ethereum-rlp = { version = "0.2", default-features = false }
ethereum-bigint = { version = "0.2", default-features = false, features = ["rlp"] }
ethereum-block = { version = "0.4", default-features = false, optional = true }
secp256k1-plus = { version = "0.5", optional = true }
libsecp256k1 = { version = "0.1", optional = true }
num-bigint = { version = "0.1", optional = true }
smallvec = { version = "0.6.8", default-features = false }
log = "0.4"
delegate = "0.1.3"

[dev-dependencies]
ethereum-hexutil = "0.2"

[features]
default = ["std", "rust-secp256k1"]
c-secp256k1 = ["secp256k1-plus", "ethereum-block/c-secp256k1"]
rust-secp256k1 = ["libsecp256k1", "ethereum-block/rust-secp256k1"]
std = ["ethereum-block-core/std", "ethereum-rlp/std", "ethereum-bigint/std", "smallvec/std", "ethereum-block"]

[workspace]
members = [
  "./cli",
  "./jsontests",
  "./regtests",
  "./gethrpc",
  "./stateful",
  "./precompiled/modexp",
  "./precompiled/bn128",
  "./network/dynamic",
  "./network/foundation",
  "./network/classic",
  "./network/ellaism",
  "./network/musicoin",
  "./network/expanse",
  "./network/ubiq",
]
