[package]
name = "ethereumvm-network"
version = "0.11.0"
description = "Network-agnostic patches for EthereumVM."
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>, Mike Lubinets <public@mersinvald.me>"]
repository = "https://github.com/ethereumproject/evm-rs"
edition = "2018"

[dependencies]
ethereumvm = { version = "0.11", path = "../..", default-features = false }
ethereumvm-precompiled-bn128 = { version = "0.11", path = "../../precompiled/bn128", default-features = false}
ethereumvm-precompiled-modexp = { version = "0.11", path = "../../precompiled/modexp", default-features = false }
ethereum-bigint = { version = "0.2", default-features = false }

[features]
default = ["std", "rust-secp256k1"]
rlp = ["ethereum-bigint/rlp"]
c-secp256k1 = ["ethereumvm/c-secp256k1", "ethereumvm-precompiled-bn128/c-secp256k1", "ethereumvm-precompiled-modexp/c-secp256k1"]
rust-secp256k1 = ["ethereumvm/rust-secp256k1", "ethereumvm-precompiled-bn128/rust-secp256k1", "ethereumvm-precompiled-modexp/rust-secp256k1"]
std = ["ethereumvm/std"]
