[package]
name = "evm-precompiled-bn128"
version = "0.11.0-beta.2"
description = "bn128 precompiled contracts for SputnikVM."
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
repository = "https://github.com/etclabscore/sputnikvm"
edition = "2018"

[dependencies]
evm = { version = "0.11.0-beta.2", path = "../..", default-features = false }
ethereum-bigint = { version = "0.2", default-features = false }
bn-plus = { version = "0.4" }

[features]
default = ["std", "rust-secp256k1"]
rlp = ["ethereum-bigint/rlp"]
c-secp256k1 = ["evm/c-secp256k1"]
rust-secp256k1 = ["evm/rust-secp256k1"]
std = ["evm/std"]
